/* Automatically generated by create_config - do not modify */
#define CONFIG_QEMU_INTERP_PREFIX "/usr/gnemul/qemu-i386"
#define TARGET_ARCH "i386"
#define TARGET_I386 1
#define CONFIG_USER_ONLY 1
#define CONFIG_LINUX_USER 1
#define CONFIG_NOSOFTFLOAT 1
#define CONFIG_USE_NPTL 1
#define CONFIG_USE_GUEST_BASE 1
#define CONFIG_I386_DIS 1
#define CONFIG_I386_DIS 1
